[project]
name = "sgr-patch"
version = "0.1.0"
description = "Schema-Guided Reasoning application"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.7",
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"
